/* Season-specific NCAA roster classes and documented player origins. */
(function(){
let data=null,pending=null;
async function enrich(raw){if(!data){pending=pending||fetch('ncaa-rosters.json?v=20260913',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('NCAA roster update could not load');return r.json();}).then(d=>data=d).catch(e=>{pending=null;throw e;});await pending;}apply(raw);}
function apply(raw){const L=raw?.leagues?.find(l=>l.meta.id==='ncaam');if(!L||!data)return;const ids=new Set(L.players.map(p=>p.id));for(const p of data.newPlayers)if(!ids.has(p.id)){L.players.push({...p});ids.add(p.id);}for(const t of data.teams){let old=L.teams.find(x=>x.code===t.code);if(!old){old={code:t.code,name:t.name};L.teams.push(old);}old.country='United States';if(!old.logo)old.logo=t.logo;}
for(const p of L.players){const r=data.records[p.id];if(!r)continue;p._ncaa=r;for(const k of ['img','height','weight'])if(!p[k]&&r[k])p[k]=r[k];}L.meta.ncaaRosterCoverage={checked:data.teamsChecked,published:data.teamsPublished,checkedAt:data.checkedAt};Object.assign(L.meta,{rosterSeason:data.rosterSeason,statsSeason:data.statsSeason,rosterUpdatedAt:data.checkedAt,rosterStatus:'imported'});}
function info(p,season='2026-27'){return p?._ncaa?.seasons?.[season]||(p?._grp||[]).map(x=>x._ncaa?.seasons?.[season]).find(Boolean)||null;}
function key(p){const r=info(p);return r?canonKey('ncaam|'+r.teamCode):null;}
function profileHTML(p){const r=info(p);if(!r)return '';return '<div class="ncaa-profile-info"><span class="ph-pill">'+esc(r.classLabel)+' · 2026/27</span><span class="ph-pill">'+esc(r.team)+'</span>'+(r.origin?.country?'<span class="ph-pill" title="'+escAttr(r.origin.basis)+'">Origin: '+esc(r.origin.country)+'</span>':'')+'<a class="ph-pill" href="'+escAttr(r.profile||r.source)+'" target="_blank" rel="noopener">School profile ↗</a></div>';}
function selectRows(L,st){const seen=new Set();return L.players.filter(p=>{const r=info(p,st.rosterSeason);if(!r)return false;const ident=p._ncaa?.espnId||p.id;if(seen.has(ident))return false;seen.add(ident);if(st.classYear==='Senior+'&&!['Senior','Graduate','Fifth year','Sixth year'].includes(r.classYear))return false;if(st.classYear&&st.classYear!=='Senior+'&&(r.classYear||'Unknown')!==st.classYear)return false;if(st.region&&r.origin?.region!==st.region)return false;if(st.role&&p.role!==st.role)return false;if(st.q&&!String(p.name+' '+r.team).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(st.q.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')))return false;return true;});}
function stat(p,k,L,season){return L.meta.season===season?p[k]:null;}
function render(){const L=STATE.data.leagues.find(l=>l.meta.id==='ncaam');if(!L||!data)return;const st=STATE.ncaa||(STATE.ncaa={rosterSeason:'2026-27',statsSeason:L.meta.season,classYear:'',region:'',role:'',q:'',sort:'ppg',dir:-1,limit:250});const cols=[['ppg','PPG'],['rpg','RPG'],['apg','APG'],['spg','SPG'],['bpg','BPG'],['fgp','FG%'],['f3p','3P%'],['ftp','FT%'],['mpg','MIN'],['g','GP']];
let rows=selectRows(L,st);rows.sort((a,b)=>{const x=stat(a,st.sort,L,st.statsSeason),y=stat(b,st.sort,L,st.statsSeason);if(x==null&&y==null)return a.name.localeCompare(b.name);if(x==null)return 1;if(y==null)return -1;return (x-y)*st.dir||a.name.localeCompare(b.name);});const opt=(v,label,selected)=>'<option value="'+escAttr(v)+'"'+(v===selected?' selected':'')+'>'+esc(label)+'</option>';const classes=['Freshman','Sophomore','Junior','Senior','Graduate','Fifth year','Sixth year','Senior+','Unknown'];const seasons=[...new Set(['2026-27','2025-26',L.meta.season])];
$('#app').innerHTML='<div class="view ncaa-view"><h1 class="title">Other leagues</h1><div class="opLgBar">'+otherLeagues().map(o=>'<button class="opLgTab'+(o.meta.id==='ncaam'?' on':'')+'" data-lg="'+escAttr(o.meta.id)+'">'+esc(o.meta.name)+'</button>').join('')+'</div><div class="opHero"><div class="opHeroT">NCAA D1</div><div class="opHeroM">2026/27 school rosters: '+data.teamsPublished+' of '+data.teamsChecked+' teams verified · Checked '+esc(data.checkedAt.slice(0,10))+'</div></div><div class="controls ncaa-controls">'+
'<label>Roster / class season<select id="ncaaRoster">'+['2026-27','2025-26'].map(y=>opt(y,y.replace('-','/'),st.rosterSeason)).join('')+'</select></label>'+ 
'<label>Statistics season<select id="ncaaStats">'+seasons.map(y=>opt(y,y.replace('-','/')+(y!==L.meta.season?' — no stats yet':''),st.statsSeason)).join('')+'</select></label>'+ 
'<label>Class<select id="ncaaClass">'+opt('','All class years',st.classYear)+classes.map(c=>opt(c,c==='Senior+'?'Senior + graduate / later years':c,st.classYear)).join('')+'</select></label>'+ 
'<label>Player origin<select id="ncaaRegion">'+opt('','All origins',st.region)+opt('Europe','Europe',st.region)+opt('Other','Outside Europe',st.region)+opt('Unknown','Unknown origin',st.region)+'</select></label>'+ 
'<label>Position<select id="ncaaRole">'+opt('','All positions',st.role)+['Guard','Forward','Big'].map(c=>opt(c,c,st.role)).join('')+'</select></label>'+ 
'<label>Search<input id="ncaaSearch" placeholder="Player or school" value="'+escAttr(st.q)+'"></label><button class="fchip" id="ncaaClear">Clear filters</button></div>'+ 
'<div class="hint ncaa-context"><b>'+rows.length+' players</b> · Classes and teams: '+esc(st.rosterSeason.replace('-','/'))+' · Stats: '+esc(st.statsSeason.replace('-','/'))+'. '+(st.statsSeason!==L.meta.season?'Statistics for this season have not been imported yet. ':'')+'Origin uses the school-listed hometown or recorded birthplace; it does not establish citizenship. Unverified rosters are excluded.</div>'+ 
'<div class="agtableWrap"><table class="opTbl"><thead><tr><th>Player</th><th>Class</th><th>Origin</th><th>School</th>'+cols.map(([k,l])=>'<th class="num opSort" data-sort="'+k+'">'+l+(st.sort===k?(st.dir===-1?' ↓':' ↑'):'')+'</th>').join('')+'</tr></thead><tbody>'+rows.slice(0,st.limit).map(p=>{const r=info(p,st.rosterSeason),ph=photoOf(p);return '<tr data-id="'+escAttr(p.id)+'"><td class="opN"><span class="opInner"><span class="agpPhoto'+(ph?'':' noimg')+'">'+(ph?'<img src="'+escAttr(ph)+'" loading="lazy" alt="" onerror="this.parentNode.classList.add(\'noimg\');this.remove()">':esc(initials(p.name)))+'</span><span class="opName">'+esc(p.name)+'</span></span></td><td>'+esc(r.classLabel)+'</td><td title="'+escAttr(r.origin?.basis||'Not recorded')+'">'+esc(r.origin?.country||'—')+'</td><td>'+esc(r.team)+'</td>'+cols.map(([k])=>{const v=stat(p,k,L,st.statsSeason);return '<td class="num">'+(v==null?'—':Number.isInteger(v)?v:Number(v).toFixed(1))+'</td>';}).join('')+'</tr>';}).join('')+(rows.length?'':'<tr><td colspan="14" class="empty">No players match these filters.</td></tr>')+'</tbody></table></div>'+(rows.length>st.limit?'<button class="btn" id="ncaaMore">Show more ('+st.limit+' of '+rows.length+')</button>':'')+'</div>';
$$('.opLgTab').forEach(b=>b.onclick=()=>{STATE.oth.lg=b.dataset.lg;renderExhib();});for(const [id,k]of [['ncaaRoster','rosterSeason'],['ncaaStats','statsSeason'],['ncaaClass','classYear'],['ncaaRegion','region'],['ncaaRole','role']])$('#'+id).onchange=e=>{st[k]=e.target.value;st.limit=250;render();};$('#ncaaSearch').oninput=e=>{st.q=e.target.value;const pos=e.target.selectionStart;st.limit=250;render();const q=$('#ncaaSearch');q.focus();q.setSelectionRange(pos,pos);};$('#ncaaClear').onclick=()=>{st.q=st.classYear=st.region=st.role='';st.limit=250;render();};$$('.opSort').forEach(b=>b.onclick=()=>{if(st.sort===b.dataset.sort)st.dir*=-1;else{st.sort=b.dataset.sort;st.dir=-1;}render();});$$('.opTbl tbody tr[data-id]').forEach(tr=>tr.onclick=()=>openProfile(tr.dataset.id));if($('#ncaaMore'))$('#ncaaMore').onclick=()=>{st.limit+=250;render();};}
window.EuroScoutNCAA={enrich,apply,info,key,profileHTML,selectRows,stat,render,ready:()=>!!data};
})();
