/* Availability evidence is separate from scouting notes and manual roster assignments. */
(function(){
'use strict';
const SEASON='2026/27',START='2026-05-01',KEY='euroscout:market-searches:v1',STATEKEY='euroscout:market-filters:v1';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const day=()=>new Date().toISOString().slice(0,10),safeURL=u=>{try{const x=new URL(u);return /^https?:$/.test(x.protocol)?x.href:'';}catch{return '';}};
const validDate=s=>/^\d{4}-\d{2}-\d{2}$/.test(s||'')&&!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s&&s<=day();
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f;}catch{return f;}};
const defaults=()=>({q:'',position:'Big',more:true,broad:false,status:'candidates',league:'',country:'',level:'',profile:'',ageMin:'',ageMax:'',heightMin:'',heightMax:'',gamesMin:'',minutesMin:'',sort:'grade',arch:'',archMin:25,filters:[],page:1});
let f={...defaults(),...read(STATEKEY,{})},review=window.EUROSCOUT_MARKET_REVIEW||{checkedAt:'',items:[]},feed={date:'',fetched:'',error:'',busy:false},news=[];
// Open the main filters at each visit, including for users with an older collapsed preference.
f.more=true;if(f.position==='C')f.position='Big';
const many=v=>Array.isArray(v)?v.map(String):v==null||v===''?[]:[String(v)];
function migrate(){for(const k of ['league','country','level','arch'])f[k]=many(f[k]);f.country=[...new Set(f.country.map(EuroScoutCountries.canonical).filter(Boolean))];f.profile='';}migrate();
if(f.status==='unknown'||f.status==='departed')f.status='presumed';
const save=()=>{try{localStorage.setItem(STATEKEY,JSON.stringify(f));}catch{toast('Could not save filters on this device.');}};
let newsIndex=new Map();
function exactNews(p,items=news){const ids=new Set([p.name,...(p._grp||[]).map(x=>x.name)].map(norm));const candidates=items===news?[...ids].flatMap(k=>newsIndex.get(k)||[]):items.filter(t=>ids.has(norm(t.player)));return [...new Set(candidates)].filter(t=>{if(t.birth_year&&p.born&&+t.birth_year!==+p.born)return false;const matches=(playerNameIndex().get(normNm(t.player))||[]).filter(x=>!t.birth_year||x.born&&+x.born===+t.birth_year);return new Set(matches.map(gid)).size<=1;}).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));}
/* The previous single-surname fallback could join unrelated players. Never use it. */
buildTransferIndex=function(items){news=(items||[]).filter(t=>t&&t.player&&t.status&&(!t.date||validDate(t.date))).slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));newsIndex=new Map();for(const t of news){const k=norm(t.player);if(!newsIndex.has(k))newsIndex.set(k,[]);newsIndex.get(k).push(t);}TRANSFERS=new Map();TRANSFERS_SUR=new Map();CLUB_LG=new Map();for(const t of news){const k=normNm(t.player);if(!TRANSFERS.has(k))TRANSFERS.set(k,t);if(t.to&&t.league&&!/free agent/i.test(t.to))CLUB_LG.set(normClub(t.to),t.league);}TRANSFERS_LOADED=news.length>0;};
nextOf=function(p){if(!p)return null;const t=exactNews(p)[0];if(!t)return null;let kind=t.status,club=t.to;if(kind==='left'){kind=!club||/free agent|unknown/i.test(club)?'available':'signed';if(kind==='available')club=null;}return {kind,club,from:t.from,contract:t.contract,source:t.source_name,url:safeURL(t.source_url),league:t.league,date:t.date};};
/* Reject ambiguous same-name people when applying existing auto-transfer records. */
playerForTransfer=function(t){let list=playerNameIndex().get(normNm(t.player))||[];if(t.birth_year)list=list.filter(p=>p.born&&+p.born===+t.birth_year);const groups=new Map(list.map(p=>[gid(p),p]));return groups.size===1?[...groups.values()][0]:null;};
function auditFor(p){const ids=new Set([p.id,gid(p),...(p._grp||[]).map(x=>x.id)]);return (review.items||[]).find(t=>(t.ids||[]).some(id=>ids.has(id))&&(!t.born||!p.born||+t.born===+p.born));}
let searchedReview, searchedIds=new Set();
function wasSearched(p){if(searchedReview!==review){searchedReview=review;searchedIds=new Set(review.searchedIds||[]);}return [p.id,gid(p),...(p._grp||[]).map(x=>x.id)].some(id=>searchedIds.has(id));}
function evidence(p,m,mb){const a=auditFor(p),assigned=effective26keys(p,m,mb||next26bGet()),retired=statusOf(p,m)===STATUS_RETIRED;
 if(statusOf(p,m)===STATUS_FREE)return {status:'available',label:'Free agent',note:'Manually recorded in the 2026/27 roster editor',checked:'',url:''};
 if(retired)return {status:'retired',label:'Retired',note:'Recorded career status',checked:'',url:''};
 if(assigned.length){const club=clubByKey(assigned[0]);return {status:'signed',label:'Signed',club:club&&club.name||assigned[0],note:'Saved 2026/27 roster assignment',checked:'',url:''};}
 const events=exactNews(p).filter(t=>validDate(t.date)&&t.date>=START&&['signed','extended','left','available','retired'].includes(t.status)&&(!['signed','extended'].includes(t.status)||t.to&&!/unknown|free agent|^\s*\?\s*$/i.test(t.to)));
 let e=a?{...a,checked:a.checkedAt||review.checkedAt,url:safeURL(a.url)}:null;
 const latest=events.find(t=>!e||t.date>(e.date||e.checked||''));
 if(latest){let s=latest.status==='left'?(!latest.to||/free agent|unknown/i.test(latest.to)?'departed':'signed'):latest.status==='extended'?'signed':latest.status; if(s==='signed'&&!latest.to)s='unknown';e={status:s,club:latest.to||'',date:latest.date,checked:'',url:safeURL(latest.source_url),source:latest.source_name||'Transfer feed',note:'Transfer-feed record; check the linked announcement.'};}
 if(e&&e.status==='retired')return {...e,label:'Retired'};
 if(e&&e.status==='signed')return {...e,label:'Signed'};

 if(e){if(['unknown','departed'].includes(e.status))return {...e,status:'presumed',label:'Free agent · presumed',note:(e.note?e.note+' ':'')+'No confirmed destination. Kept in the free-agent pool until a signing or roster is recorded.'};return {...e,label:({available:'Reported available',departed:'Departure reported',unknown:'Unverified',retired:'Retired'})[e.status]||'Unverified'};}
 const rumor=exactNews(p).find(t=>t.status==='rumor'&&t.date>=START),searched=wasSearched(p);return {status:'presumed',label:'Free agent · presumed',club:'',checked:searched?review.coverage?.checkedAt||review.checkedAt:'',url:safeURL(rumor&&rumor.source_url),note:rumor?'Rumour only — no confirmed signing.':searched?'Web search completed; current club or availability remains unverified.':'No current contract evidence recorded. Availability is presumed until a signing or roster is recorded.'};
}
function center(p){return [p,...(p._grp||[])].some(x=>/(^|[^a-z])(c|center|centre|pivot)([^a-z]|$)/i.test(x.pos||''));}
function broadBig(p){return !center(p)&&p.role==='Big'&&(!p.pos||/^(big|forward.center|f.c)$/i.test(p.pos));}
function value(p,key){if(key==='grade')return statGradeOverall(p);if(key==='threeAttempts'){if(p.g>0&&Number.isFinite(p.t_f3a))return p.t_f3a/p.g;const a=String(p.f3ma||'').split('-');return p.g>0&&a.length===2?+a[1]/p.g:null;}return p[key];}
const profiles={rim:{name:'Rim protection',text:'Blocks ≥ 1/game · 10+ games',limits:[['bpg',1,99],['g',10,999]]},rebound:{name:'Rebounding',text:'Rebounds ≥ 6/game · 10+ games',limits:[['rpg',6,99],['g',10,999]]},stretch:{name:'Stretch 5',text:'3P ≥ 33% · 1.5+ attempts/game · 10+ games',limits:[['f3p',33,100],['threeAttempts',1.5,99],['g',10,999]]},pass:{name:'Passing big',text:'Assists ≥ 2/game · 10+ games',limits:[['apg',2,99],['g',10,999]]},young:{name:'Development',text:'Age ≤ 24 · 10+ games',limits:[['age',16,24],['g',10,999]]}};
function filterRows(){const m=next26Get(),mb=next26bGet();let rows=scoutPool().map(p=>({p,e:evidence(p,m,mb)}));
 rows=rows.filter(({p,e})=>{if(f.status==='candidates'&&['signed','retired'].includes(e.status))return false;if(f.status!=='candidates'&&f.status!=='all'&&e.status!==f.status)return false;
 if(f.position==='C'&&!center(p)&&!(f.broad&&broadBig(p)))return false;if(['Guard','Forward','Big'].includes(f.position)&&p.role!==f.position)return false;
 if(f.q&&!norm([p.name,p.teamName,p.agent,p.agency].join(' ')).includes(norm(f.q)))return false;if(f.league.length&&![p,...(p._grp||[])].some(x=>f.league.includes(x.league)))return false;
 if(f.country.length&&!f.country.includes(p.country||''))return false;if(f.level.length&&!f.level.includes(String(levelBand(p)?.i)))return false;
 const ranges=[['age',f.ageMin,f.ageMax],['height',f.heightMin,f.heightMax],['g',f.gamesMin,''],['mpg',f.minutesMin,''],...(f.filters||[]).map(x=>[x.key,x.min,x.max])];
 if(ranges.some(([k,lo,hi])=>{if(lo===''&&hi==='')return false;const v=value(p,k);return v==null||!Number.isFinite(+v)||(lo!==''&&v<+lo)||(hi!==''&&v>+hi);}))return false;
 if(f.arch.length&&!f.arch.some(key=>{const [ai,band]=key.split(':').map(Number);return p.arch&&p.arch[ai]!=null&&p.arch[ai]>=+f.archMin&&!(band!=null&&ARCHETYPES[ai]?.roleBands&&p.role!==ROLE_ORDER[band]);}))return false;return true;});
 rows.sort((a,b)=>{if(f.sort==='name')return a.p.name.localeCompare(b.p.name);if(f.sort==='checked')return String(b.e.checked||'').localeCompare(String(a.e.checked||''))||a.p.name.localeCompare(b.p.name);const k=f.sort==='young'?'age':f.sort,va=value(a.p,k),vb=value(b.p,k);if(va==null)return vb==null?0:1;if(vb==null)return -1;return (f.sort==='young'?va-vb:vb-va)||a.p.name.localeCompare(b.p.name);});return rows;
}
function options(list,current){return list.map(([v,l])=>`<option value="${escAttr(String(v))}"${String(v)===String(current)?' selected':''}>${esc(l)}</option>`).join('');}
const select=(id,label,list,v)=>`<label>${label}<select id="${id}">${options(list,v)}</select></label>`;
const multi=(id,label,list,values)=>'<div class="fa-multi-field"><span>'+esc(label)+'</span><details class="fa-multi" id="'+id+'"><summary>'+esc(values.length?values.length===1?(list.find(x=>String(x[0])===values[0])?.[1]||values[0]):values.length+' selected':'Any')+'</summary><div class="fa-multi-menu"><input type="search" class="fa-filter-search" aria-label="Search '+escAttr(label)+'" placeholder="Search…" autocomplete="off"><p class="fa-no-matches" hidden>No matching options</p><button type="button" data-clear-multi="'+id+'">Clear selection</button>'+list.map(([v,l])=>'<label><input type="checkbox" value="'+escAttr(String(v))+'" '+(values.includes(String(v))?'checked':'')+'>'+esc(l)+'</label>').join('')+'</div></details></div>';
const multiQueries={};
function wireMulti(){const keys={faLeague:'league',faCountry:'country',faLevel:'level',faArch:'arch'};for(const [id,key]of Object.entries(keys)){const el=document.getElementById(id);el.addEventListener('toggle',()=>{if(el.open)document.querySelectorAll('.fa-multi[open]').forEach(x=>{if(x!==el)x.open=false;});});const search=el.querySelector('.fa-filter-search');search.value=multiQueries[id]||'';const searchOptions=()=>{multiQueries[id]=search.value;let count=0;el.querySelectorAll('.fa-multi-menu label').forEach(l=>{l.hidden=!norm(l.textContent+' '+l.querySelector('input').value).includes(norm(search.value));if(!l.hidden)count++;});el.querySelector('.fa-no-matches').hidden=count>0;};search.oninput=searchOptions;searchOptions();el.querySelectorAll('input[type=checkbox]').forEach(input=>input.onchange=()=>{f[key]=[...el.querySelectorAll('input:checked')].map(x=>x.value);const top=el.querySelector('.fa-multi-menu').scrollTop;redraw();const next=document.getElementById(id);next.open=true;next.querySelector('.fa-multi-menu').scrollTop=top;next.querySelector('input[value="'+CSS.escape(input.value)+'"]')?.focus();});el.querySelector('button').onclick=()=>{f[key]=[];redraw();document.getElementById(id).querySelector('summary').focus();};}}
document.addEventListener('click',e=>document.querySelectorAll('.fa-multi[open]').forEach(el=>{if(!el.contains(e.target))el.open=false;}));
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.fa-multi[open]').forEach(el=>{el.open=false;el.querySelector('summary').focus();});});
const num=(key,label)=>`<label>${label}<input type="number" min="0" id="fa-${key}" value="${escAttr(String(f[key]))}" placeholder="Any"></label>`;
function sourceHTML(e){return `${e.club?'<strong>'+esc(e.club)+'</strong>':''}<span class="fa-badge ${e.status}">${esc(e.label)}</span><small>${e.date?'News '+esc(e.date)+' · ':''}${e.checked?'Checked '+esc(e.checked):'Not individually checked'}</small>${e.url?'<a target="_blank" rel="noopener noreferrer" href="'+escAttr(e.url)+'">'+esc(e.source||'Source')+' ↗</a>':''}<small>${esc(e.note||'')}</small>`;}
function redraw(reset=true){if(reset)f.page=1;save();renderFreeAgents();}
renderFreeAgents=function(){STATE.view='freeagents';STATE.teamsMode='next';const rows=filterRows(),count=rows.length,pages=Math.max(1,Math.ceil(count/30));f.page=Math.min(Math.max(1,+f.page||1),pages);const shown=rows.slice((f.page-1)*30,f.page*30),searches=read(KEY,[]);
 const countries=[...new Set(scoutPool().map(p=>p.country).filter(Boolean))].sort(),lgs=(STATE.data.leagues||[]).filter(l=>l.players?.length);
 $('#app').innerHTML=`<div class="view fa-view"><div class="fa-heading"><div><h1 class="title">Free-agent search <small>${SEASON}</small></h1><p>Find candidates. Confirm their availability before approaching them.</p></div><div class="fa-actions"><button id="faRefresh" ${feed.busy?'disabled':''}>${feed.busy?'Refreshing…':'↻ Refresh status feed'}</button><button id="faReset">Reset filters</button><button id="faExport">Export results</button></div></div>
 <div class="fa-freshness" role="status">${feed.error?esc(feed.error)+' · ':''}Research checked ${esc(review.checkedAt||'not loaded')}${review.coverage?' · '+esc(review.coverage.searched)+' names searched · '+esc(review.coverage.withEvidence)+' with sourced findings':''} · Transfer feed ${esc(feed.date||'loading')} ${feed.fetched?'· Last fetched '+esc(feed.fetched):''}. No known destination is treated as presumed free agency. Refresh reloads the feed and saved research.</div>
 <div class="fa-main-filters"><label class="fa-query">Search<input id="faQ" value="${escAttr(f.q)}" placeholder="Player, club or agency"></label>${select('faPosition','Position',[['','All positions'],...ROLE_OPTS],f.position)}${select('faStatus','Availability',[['candidates','Candidates · verify'],['available','Reported available'],['presumed','Free agent · presumed'],['signed','Signed / rostered'],['all','All statuses']],f.status)}${select('faSort','Sort',[['grade','Stat grade ↓'],['rpg','Rebounds ↓'],['bpg','Blocks ↓'],['height','Height ↓'],['young','Age ↑'],['name','Name A–Z'],['checked','Recently checked']],f.sort)}</div>
 <details class="fa-more" ${f.more?'open':''}><summary>More filters · size, age, league, nationality, level and statistics</summary><div class="fa-filter-grid">${num('heightMin','Min height · cm')}${num('heightMax','Max height · cm')}${num('ageMin','Min age')}${num('ageMax','Max age')}${num('gamesMin','Min games')}${num('minutesMin','Min minutes / game')}${multi('faLeague','League experience',lgs.map(l=>[l.meta.id,l.meta.name]),f.league)}${multi('faCountry','Recorded nationality',countries.map(c=>[c,EuroScoutCountries.label(c)]),f.country)}${multi('faLevel','Projected level',LEVEL_BANDS.map((l,i)=>[i,l]),f.level)}${multi('faArch','Playing style',ARCH_FILTERS.map(a=>[a.key,a.label]),f.arch)}<label>Min style match %<input type="number" id="faArchMin" min="0" max="100" value="${f.archMin}"></label>${select('faAdd','Add statistic',[['','Choose a statistic…'],...FILTER_STATS.filter(s=>!f.filters.some(x=>x.key===s.key)).map(s=>[s.key,s.label])],'')}</div><p class="hint">Nationality is the recorded country, not passport or local-player eligibility. Missing values are excluded when their filter is active. Stats use each player’s representative competition.</p><div class="fa-ranges">${f.filters.map((x,i)=>`<div>${esc(FILTER_STATS.find(s=>s.key===x.key)?.label||x.key)} <input aria-label="Minimum ${escAttr(x.key)}" type="number" data-range="${i}" data-bound="min" value="${x.min}"> to <input aria-label="Maximum ${escAttr(x.key)}" type="number" data-range="${i}" data-bound="max" value="${x.max}"><button data-remove="${i}" aria-label="Remove ${escAttr(x.key)} filter">×</button></div>`).join('')}</div></details>
 <details class="fa-saved-wrap"><summary>Saved searches</summary><div class="fa-saved">${select('faSaved','Saved searches on this device',[['','Choose saved search…'],...searches.map((x,i)=>[i,x.name])],'')}<label>Save these filters<input id="faSearchName" placeholder="e.g. Rebounding center under 28" maxlength="70"></label><button id="faSaveSearch">Save search</button></div></details>
 <div class="fa-results-head"><strong>${count} matches</strong><span>Signed players are excluded from candidates. Presumed free agents have no confirmed destination.</span><button type="button" onclick="document.getElementById('faExport').click()">Export results</button><button id="faCompare">Compare (${compareCount()}/4)</button></div>
 <div class="fa-results">${shown.map(({p,e})=>`<article class="fa-card" data-player="${escAttr(p.id)}"><div class="fa-player"><button class="fa-open" data-open="${escAttr(p.id)}">${photoOf(p)?'<img src="'+escAttr(photoOf(p))+'" loading="lazy" alt="" onerror="this.style.display=&quot;none&quot;">':''}<span><strong>${esc(p.name)}</strong><small>${esc(p.pos||p.role||'Position unknown')}${broadBig(p)?' · center unconfirmed':''} · ${p.height?esc(String(p.height))+' cm':'Height unknown'} · ${p.age!=null?esc(String(p.age))+' years':'Age unknown'}</small><small>${esc(EuroScoutCountries.label(p.country))} · Last recorded: ${esc(p.teamName||'—')}</small></span></button><small>${esc(leagueOf(p).meta.name||p.league)} · ${esc(leagueOf(p).meta.season||'')} · ${p.g||0} games</small></div><div class="fa-statline">${[['ppg','PTS'],['rpg','REB'],['bpg','BLK'],['apg','AST'],['grade','GRADE']].map(([k,l])=>'<div><b>'+ (value(p,k)!=null?Number(value(p,k)).toFixed(1):'—')+'</b><small>'+l+'</small></div>').join('')}</div><div class="fa-evidence">${sourceHTML(e)}</div><div class="fa-card-actions"><button data-compare="${escAttr(p.id)}">${inCompare(p.id)?'✓ In compare':'+ Compare'}</button><button data-open="${escAttr(p.id)}">Open profile ↗</button><a href="${escAttr(safeURL(eurobasketURL(p)))}" target="_blank" rel="noopener noreferrer">Eurobasket ↗</a></div></article>`).join('')||'<p class="empty">No players match. Broaden the filters or include unverified candidates.</p>'}</div><div class="fa-pages"><button id="faPrev" ${f.page<=1?'disabled':''}>← Previous</button><span>Page ${f.page} of ${pages} · ${count?'Showing '+((f.page-1)*30+1)+'–'+Math.min(f.page*30,count):'0 results'}</span><button id="faNext" ${f.page>=pages?'disabled':''}>Next →</button></div></div>`;
 wireMulti();
 const bind=(id,event,fn)=>document.getElementById(id)?.addEventListener(event,fn);
 bind('faQ','input',e=>{f.q=e.target.value;const pos=e.target.selectionStart;redraw();$('#faQ').focus();$('#faQ').setSelectionRange(pos,pos);});
 for(const [id,k] of [['faPosition','position'],['faStatus','status'],['faSort','sort']])bind(id,'change',e=>{f[k]=e.target.value;redraw();});
 for(const key of ['heightMin','heightMax','ageMin','ageMax','gamesMin','minutesMin'])bind('fa-'+key,'change',e=>{f[key]=e.target.value;redraw();});
 bind('faArchMin','change',e=>{f.archMin=Math.max(0,Math.min(100,+e.target.value));redraw();});bind('faBroad','change',e=>{f.broad=e.target.checked;redraw();});
 $('.fa-more').addEventListener('toggle',e=>{f.more=e.target.open;save();});
 $$('[data-preset]').forEach(b=>b.onclick=()=>{f.profile=b.dataset.preset;if(f.profile)f.position='Big';redraw();});bind('faReset','click',()=>{f=defaults();migrate();redraw();});
 bind('faAdd','change',e=>{const st=FILTER_STATS.find(x=>x.key===e.target.value);if(st){f.filters.push({key:st.key,min:st.min,max:st.max});redraw();}});
 $$('[data-range]').forEach(n=>n.onchange=()=>{f.filters[+n.dataset.range][n.dataset.bound]=n.value===''?'':+n.value;redraw();});$$('[data-remove]').forEach(n=>n.onclick=()=>{f.filters.splice(+n.dataset.remove,1);redraw();});
 bind('faSaveSearch','click',()=>{const name=$('#faSearchName').value.trim();if(!name){toast('Name your saved search first.');return;}const items=read(KEY,[]).filter(x=>x.name!==name);items.push({name,filters:{...f,page:1}});localStorage.setItem(KEY,JSON.stringify(items.slice(-30)));redraw(false);toast('Search saved on this device.');});bind('faSaved','change',e=>{if(e.target.value==='')return;const s=read(KEY,[])[+e.target.value];if(s){f={...defaults(),...s.filters,more:true};if(f.position==='C')f.position='Big';migrate();redraw();}});
 $$('[data-open]').forEach(b=>b.onclick=()=>openProfile(b.dataset.open));$$('[data-compare]').forEach(b=>b.onclick=()=>{toggleCompare(b.dataset.compare);redraw(false);});bind('faCompare','click',openCompare);bind('faRefresh','click',refreshMarket);
 bind('faPrev','click',()=>{f.page--;redraw(false);$('.fa-results-head').scrollIntoView({block:'start'});});bind('faNext','click',()=>{f.page++;redraw(false);$('.fa-results-head').scrollIntoView({block:'start'});});
 bind('faExport','click',()=>EuroScoutExport.menu());
 if(typeof esAfterRender==='function')esAfterRender();paintCompareBar();
};
function installNav(){if(!$('#tabs'))return;let b=$('#faNav');if(!b){b=document.createElement('button');b.id='faNav';b.dataset.view='freeagents';b.textContent='Free agents';}b.onclick=()=>{f.more=true;STATE.view='freeagents';renderFreeAgents();};const t=$('#tabs [data-view=teams]');if(t&&t.nextElementSibling!==b)t.after(b);}
const baseRender=render;render=function(){installNav();if(STATE.view==='freeagents')renderFreeAgents();else baseRender();};window.render=render;
async function getJSON(url){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),10000);try{const r=await fetch(url,{cache:'no-store',signal:ctl.signal});if(!r.ok)throw Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(timer);}}
async function refreshMarket(){if(feed.busy)return;feed.busy=true;feed.error='';if(STATE.view==='freeagents')renderFreeAgents();const results=await Promise.allSettled([getJSON('https://turkmarkoo.github.io/euroball-tracker/transfers_all.json'),getJSON('data/free-agent-review.json')]);let messages=[];if(results[0].status==='fulfilled'&&Array.isArray(results[0].value.items)){const j=results[0].value;buildTransferIndex([...(STATE.data?.transfers||[]),...j.items]);feed.date=String(j.generated_at||'date unavailable').slice(0,10);feed.fetched=new Date().toLocaleString();}else messages.push('Feed unavailable; previous evidence retained');if(results[1].status==='fulfilled'&&Array.isArray(results[1].value.items)&&results[1].value.season===SEASON)review=results[1].value;else messages.push('Using bundled research');feed.error=messages.join(' · ');feed.busy=false;if(STATE.view==='freeagents')renderFreeAgents();}
/* A refresh must not silently alter the user's saved roster map. */
loadTransfers=async function(){buildTransferIndex(STATE.data?.transfers||[]);await refreshMarket();try{updateTransferBadge();}catch{}};
const baseCell=next26CellHTML;next26CellHTML=function(p){const e=evidence(p,next26Get());if(effective26(p))return baseCell(p);return '<div class="fa-profile-evidence">'+sourceHTML(e)+'</div><button onclick="openTeamPickerProfile(&quot;'+escAttr(p.id)+'&quot;)">Update roster assignment</button>';};
nextBadge=function(p,big){const e=evidence(p,next26Get());if(e.status==='unknown'&&!e.url)return '';return '<span class="fa-badge '+escAttr(e.status)+(big?' big':'')+'" title="'+escAttr([e.source,e.date,e.note].filter(Boolean).join(' · '))+'">'+esc(e.label)+(e.club?' → '+esc(e.club):'')+'</span>';};
careerStatus=function(p,m){const e=evidence(p,m||next26Get());return ['signed','retired'].includes(e.status)?e.status:'available';};AG_ST.available.lab='Candidates · verify status';
window.marketCandidate=function(p,m,mb){return !['signed','retired'].includes(evidence(p,m||next26Get(),mb).status);};
window.EuroScoutMarket={evidence,filterRows,center,broadBig,exactNews,refresh:refreshMarket,get filters(){return f;},get feed(){return feed;}};
installNav();
})();

// Update the visible list as soon as any roster picker saves a change.
(function(){const save=set26;let pending;set26=function(id,key){save(id,key);clearTimeout(pending);pending=setTimeout(()=>{if(STATE.view==="agencies"||STATE.view==="freeagents")render();},0);};window.set26=set26;})();
function agencyStatusControl(p,extra=''){const e=EuroScoutMarket.evidence(p,next26Get());const label=e.status==='presumed'?'Unverified':e.label;return '<'+(Store.canEdit()?'button':'span')+' class="ag-status-edit '+escAttr(e.status)+extra+'"'+(Store.canEdit()?' type="button" onclick="event.stopPropagation();openEditModal(decodeURIComponent(this.dataset.player))" data-player="'+encodeURIComponent(p.id)+'" title="Edit club or availability for 2026/27"':'')+'>'+esc(label)+(Store.canEdit()?'<small>Edit status ↗</small>':'')+'</'+(Store.canEdit()?'button':'span')+'>'; }
