/* Official FEB regular-season enrichment. Current assignments and private records are untouched. */
(function(){
function apply(raw){const pack=window.EUROSCOUT_FEB_DATA;if(!raw?.leagues||!pack)return;
for(const source of pack.leagues){let l=raw.leagues.find(l=>l.meta.id===source.meta.id);if(!l){l={meta:{...source.meta},teams:[],players:[],statMeta:{}};raw.leagues.push(l);}const teams=new Set(l.teams.map(t=>t.code));for(const t of source.teams)if(!teams.has(t.code)){l.teams.push({...t});teams.add(t.code);}for(const incoming of source.players){let old=l.players.find(p=>p.id===incoming.id);if(old){if(incoming.g>0)Object.assign(old,incoming);else for(const k of ['img','birthdate','profile_url','profile_provider'])if(!old[k])old[k]=incoming[k];}else l.players.push({...incoming});}
const keys=['ppg','rpg','apg','spg','bpg','topg','orpg','drpg','fgp','f3p','ftp','efg','ts','pir','eff','mpg','pts40','reb40','ast40','stl40','blk40','tov40'];l.statMeta=l.statMeta||{};
for(const k of keys){const vals=l.players.filter(p=>p.qualified&&Number.isFinite(p[k])).map(p=>p[k]).sort((a,b)=>a-b);if(!vals.length)continue;const mean=vals.reduce((a,b)=>a+b,0)/vals.length,sd=Math.sqrt(vals.reduce((a,b)=>a+(b-mean)**2,0)/vals.length);l.statMeta[k]={mean,sd};for(const p of l.players){p.pct=p.pct||{};p.z=p.z||{};if(!Number.isFinite(p[k])){p.pct[k]=null;p.z[k]=null;continue;}p.pct[k]=100*vals.filter(v=>v<=p[k]).length/vals.length;p.z[k]=sd?(p[k]-mean)/sd:0;}}
l.meta.playerCount=l.players.length;l.meta.qualifiedCount=l.players.filter(p=>p.qualified).length;l.meta.source=source.meta.source;l.meta.statsScope=pack.scope;
}}
function link(uni){for(const pair of window.EUROSCOUT_FEB_DATA?.links||[])uni(...pair);}
function applyCurrentRoster(raw){const pack=window.EUROSCOUT_FEB_ROSTERS_2026;if(!raw?.leagues||!pack)return;const league=raw.leagues.find(l=>l.meta.id==='feb');if(!league)return;const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();for(const team of pack.teams||[])for(const incoming of team.players||[]){let p=league.players.find(x=>norm(x.name)===norm(incoming.name));if(!p){p={id:`feb-roster-2026-${norm(incoming.name).replace(/ /g,'-')}`,name:incoming.name,league:'feb',team:team.code,teamName:team.name,role:'',pos:incoming.pos,height:incoming.height,birthdate:incoming.birthdate,born:Number(incoming.birthdate?.slice(0,4))||null,jersey:incoming.jersey,img:incoming.img||null,profile_url:incoming.profileUrl||null,profile_provider:'Movistar Estudiantes',_rosterOnly:true,_strictIdentity:true,qualified:false,gameLog:[],pct:{},z:{},g:null};league.players.push(p);}p.currentRosterSeason=pack.season;p.currentClub=team.name;p.currentRosterSource=incoming.profileUrl||team.source;if(incoming.img&&!p.img)p.img=incoming.img;if(incoming.profileUrl&&!p.profile_url)p.profile_url=incoming.profileUrl;if(incoming.height&&!p.height)p.height=incoming.height;if(incoming.birthdate&&!p.birthdate){p.birthdate=incoming.birthdate;p.born=Number(incoming.birthdate.slice(0,4));}}league.meta.currentRosterSeason=pack.season;league.meta.currentRosterChecked=pack.checkedAt;}
window.EuroScoutFEB={apply,applyCurrentRoster,link};
})();
