(function(){
'use strict';
const STATS=[['g','GP'],['mpg','MIN'],['ppg','PTS'],['rpg','REB'],['apg','AST'],['spg','STL'],['bpg','BLK'],['topg','TO'],['pir','PIR'],['eff','EFF'],['fgm','FGM'],['fga','FGA'],['fgp','FG%'],['f2m','2PM'],['f2a','2PA'],['f2p','2P%'],['f3m','3PM'],['f3a','3PA'],['f3p','3P%'],['ftm','FTM'],['fta','FTA'],['ftp','FT%'],['efg','eFG%'],['ts','TS%']];
const numeric=x=>x!==null&&x!==undefined&&x!==''&&Number.isFinite(Number(x))?Number(x):null;
const link=u=>{try{const x=new URL(u);return /^https?:$/.test(x.protocol)?x.href:'';}catch{return '';}};
const round=x=>x==null?null:Math.round(x*10)/10;
function values(p){const v={};const pair=k=>{const a=String(p[k]||'').match(/^\s*(\d+(?:\.\d+)?)\s*[-/]\s*(\d+(?:\.\d+)?)\s*$/);return a?[+a[1],+a[2]]:null;};const fg=pair('fgma'),th=pair('f3ma'),ft=pair('ftma');let divisor=null;if(fg&&th&&ft&&numeric(p.ppg)!=null&&p.g>0){const score=2*fg[0]+th[0]+ft[0],avgError=Math.abs(score-p.ppg),totalError=Math.abs(score/p.g-p.ppg),tolerance=Math.max(1,p.ppg*.12);if(Math.min(avgError,totalError)<=tolerance)divisor=avgError<=totalError?1:p.g;}
STATS.forEach(([k])=>v[k]=numeric(p[k]));for(const [made,attempts,totalMade,totalAttempts,combined]of [['fgm','fga','t_fgm','t_fga','fgma'],['f3m','f3a','t_f3m','t_f3a','f3ma'],['ftm','fta','t_ftm','t_fta','ftma']]){let m=numeric(p[totalMade]),a=numeric(p[totalAttempts]);const pair=String(p[combined]||'').match(/^\s*(\d+(?:\.\d+)?)\s*[-/]\s*(\d+(?:\.\d+)?)\s*$/);if(p.g>0){v[made]=m!=null?m/p.g:pair&&divisor?+pair[1]/divisor:null;v[attempts]=a!=null?a/p.g:pair&&divisor?+pair[2]/divisor:null;}}
 v.f2m=v.fgm!=null&&v.f3m!=null?v.fgm-v.f3m:null;v.f2a=v.fga!=null&&v.f3a!=null?v.fga-v.f3a:null;if(v.f2p==null&&v.f2a>0)v.f2p=v.f2m/v.f2a*100;return v;}
function snapshot(){return EuroScoutMarket.filterRows().map(({p,e})=>{const l=leagueOf(p)?.meta||{};return {notes:effectiveReport(p),name:p.name,position:p.pos||p.role||'',age:numeric(p.age),height:numeric(p.height),country:p.country||'',last:p.teamName||'',league:l.name||'',season:l.season||'',status:e.label||'',club:e.status==='signed'?e.club||'':'',grade:round(statGradeOverall(p)),agent:EuroScoutAgencyResearch.agentsOf(p).join(', '),agency:p.agency||'',checked:e.checked||'',news:e.date||'',source:link(e.url),eurobasket:link(eurobasketURL(p)),profile:location.href.split('#')[0]+'#p='+encodeURIComponent(p.id),stats:values(p)};});}
let loading;
async function libraries(){if(!loading)loading=Promise.all(['exceljs.min.js','jspdf.umd.min.js'].map(f=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='vendor/'+f;s.onload=resolve;s.onerror=()=>reject(Error('Could not load export tools. Reload and try again.'));document.head.appendChild(s);}))).catch(e=>{loading=null;throw e;});await loading;}
const date=()=>new Date().toISOString().slice(0,10);
function download(bytes,type,ext){const url=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=url;a.download='EuroScout-candidates-'+date()+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function criteria(){return Object.entries(EuroScoutMarket.filters).filter(([k,v])=>!['page','more','profile'].includes(k)&&v!==''&&v!==false&&(!Array.isArray(v)||v.length)).map(([k,v])=>[k,typeof v==='object'?JSON.stringify(v):String(v)]);}
async function excel(rows,includeNotes=false){await libraries();const w=new ExcelJS.Workbook();w.creator='EuroScout';w.created=new Date();
function sheet(name,cols,data){const s=w.addWorksheet(name,{views:[{state:'frozen',ySplit:5,xSplit:1,showGridLines:false}]});s.columns=cols.map(([label,width])=>({header:label,width:width||14}));s.spliceRows(1,1);s.mergeCells(1,1,1,cols.length);s.getCell('A1').value='EuroScout · '+name;s.getRow(1).height=34;s.mergeCells(2,1,2,cols.length);s.getCell('A2').value='2026/27 recruitment · Exported '+date()+' · '+rows.length+' candidates';s.getRow(2).height=24;s.mergeCells(3,1,3,cols.length);s.getCell('A3').value='Statistics are per game except GP and percentages. League and season identify the statistics source. Blank means unavailable.';s.getRow(3).height=24;s.getRow(5).values=cols.map(c=>c[0]);for(const r of data)s.addRow(r.map(x=>x==null?'':x));s.autoFilter={from:{row:5,column:1},to:{row:Math.max(5,s.rowCount),column:cols.length}};s.eachRow((row,n)=>{row.eachCell({includeEmpty:true},(c,i)=>{c.font={name:'Calibri',size:11,color:{argb:'FF24363B'}};c.alignment={vertical:'middle',wrapText:true};if(n===1||n===5){c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF24363B'}};c.font={name:'Calibri',size:n===1?18:11,bold:true,color:{argb:'FFFFFFFF'}};}else if(n>5&&n%2===0)c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF0F5F2'}};if(typeof c.value==='number')c.numFmt=Number.isInteger(c.value)?'0':'0.0';if(c.value?.hyperlink)c.font={name:'Calibri',size:11,color:{argb:'FF187059'},underline:true};});if(n>5)row.height=34;});s.pageSetup={orientation:'landscape',paperSize:9,fitToPage:true,fitToWidth:1,fitToHeight:0,printTitlesRow:'1:5'};return s;}
const href=(text,url)=>url?{text,hyperlink:url}:'';
sheet('Shortlist',[['Player',26],['Position',18],['Age',8],['Height cm',11],['Nationality',18],['Last recorded club',27],['Availability',25],['2026/27 club',27],['Grade',9],['Agent',25],['Agency',25],['Eurobasket',16],['Profile',14],['Source',14],['Checked',14]],rows.map(r=>[r.name,r.position,r.age,r.height,r.country,r.last,r.status,r.club,r.grade,r.agent,r.agency,href('Eurobasket',r.eurobasket),href('Profile',r.profile),href('Source',r.source),r.checked]));
sheet('Basic statistics',[['Player',26],['Stats league',25],['Stats season',15],...STATS.map(([,l])=>[l,10])],rows.map(r=>[r.name,r.league,r.season,...STATS.map(([k])=>round(r.stats[k]))]));
sheet('Sources',[['Player',26],['Availability',26],['News date',15],['Checked',15],['Source',35],['Eurobasket',35]],rows.map(r=>[r.name,r.status,r.news,r.checked,href(r.source,r.source),href(r.eurobasket,r.eurobasket)]));sheet('Search criteria',[['Filter',24],['Value',90]],criteria());if(includeNotes)sheet('Scouting notes',[['Player',26],['Athleticism',45],['Offense',45],['Defense',45],['Verdict',45]],rows.map(r=>[r.name,...['nAth','nOff','nDef','nProj'].map(k=>String(r.notes?.[k]||''))]));download(await w.xlsx.writeBuffer(),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','xlsx');}
let font;
async function pdfDoc(){await libraries();if(!font){const r=await fetch('vendor/NotoSans.ttf');if(!r.ok)throw Error('Could not load PDF font.');const data=new Uint8Array(await r.arrayBuffer());let s='';for(let i=0;i<data.length;i+=8192)s+=String.fromCharCode(...data.subarray(i,i+8192));font=btoa(s);}const d=new jspdf.jsPDF({orientation:'landscape',unit:'mm',format:'a4',putOnlyUsedFonts:true});d.addFileToVFS('NotoSans.ttf',font);d.addFont('NotoSans.ttf','NotoSans','normal');d.setFont('NotoSans');return d;}
function text(d,s,x,y,width,size=9){d.setFontSize(size);const lines=d.splitTextToSize(String(s??'—'),width);d.text(lines,x,y);return lines.length*size*.38;}
function head(d,title,count){d.setFillColor(36,54,59);d.rect(0,0,297,29,'F');d.setTextColor(255);text(d,'EuroScout · '+title,12,13,272,16);text(d,'2026/27 recruitment · '+date()+' · '+count+' candidates',12,23,272,9);d.setTextColor(36,54,59);}
function foot(d){const n=d.getNumberOfPages();for(let i=1;i<=n;i++){d.setPage(i);d.setDrawColor(204,214,208);d.line(12,197,285,197);d.setTextColor(90);text(d,'Per game except GP and percentages. — = unavailable. Availability requires confirmation before contact.',12,203,250,7);text(d,i+' / '+n,273,203,20,7);}}
function table(d,title,rows,columns,widths){head(d,title,rows.length);const x=12,y=39;d.setFillColor(230,238,233);d.rect(x,32,273,11,'F');let xx=x;columns.forEach((c,i)=>{text(d,c[0],xx+2,y,widths[i]-4,8);xx+=widths[i];});let yy=44;rows.forEach((r,j)=>{const vals=columns.map(c=>c[1](r));let height=10;vals.forEach((v,i)=>{d.setFontSize(8);height=Math.max(height,d.splitTextToSize(String(v??'—'),widths[i]-4).length*3.4+5);});if(yy+height>191){d.addPage();head(d,title,rows.length);yy=44;d.setFillColor(230,238,233);d.rect(x,32,273,11,'F');xx=x;columns.forEach((c,i)=>{text(d,c[0],xx+2,39,widths[i]-4,8);xx+=widths[i];});}if(j%2===0){d.setFillColor(244,247,245);d.rect(x,yy,273,height,'F');}xx=x;vals.forEach((v,i)=>{text(d,v,xx+2,yy+5,widths[i]-4,8);xx+=widths[i];});yy+=height;});}
const fmt=v=>v==null?'—':Number(v).toFixed(1).replace(/\.0$/,'');
async function pdf(rows,cards,includeNotes=false){const d=await pdfDoc();if(!cards){table(d,'Candidate comparison',rows,[['Player',r=>r.name+'\n'+r.position+' · '+(r.age??'—')+' years · '+(r.height??'—')+' cm'],['Last recorded club',r=>r.last],['Availability',r=>r.status],['Grade',r=>fmt(r.grade)],['Agent / agency',r=>[r.agent,r.agency].filter(Boolean).join('\n')],['Checked',r=>r.checked||'Not recorded']],[65,53,43,18,63,31]);for(const [label,stats]of [['Box scores',STATS.slice(0,10)],['Shooting',STATS.slice(10)]]){d.addPage();const w=(273-72)/stats.length;table(d,label,rows,[['Player / stats source',r=>r.name+'\n'+r.league+' · '+r.season],...stats.map(([k,l])=>[l,r=>fmt(r.stats[k])])],[72,...stats.map(()=>w)]);}}else{for(let i=0;i<rows.length;i++){if(i)d.addPage();const r=rows[i];head(d,'Player card',rows.length);text(d,r.name,12,43,270,20);text(d,[r.position,r.age==null?'':r.age+' years',r.height==null?'':r.height+' cm',r.country].filter(Boolean).join(' · '),12,53,270,10);text(d,'Availability: '+r.status+'   |   Grade: '+fmt(r.grade),12,64,270,11);text(d,'Last recorded club: '+r.last+'   ·   Stats: '+r.league+' '+r.season,12,74,270,9);STATS.forEach(([k,l],j)=>{const x=12+(j%8)*34.2,y=85+Math.floor(j/8)*22;d.setFillColor(240,245,242);d.rect(x,y,32,20,'F');text(d,l,x+2,y+6,28,8);text(d,fmt(r.stats[k]),x+2,y+15,28,12);});text(d,'Representation: '+[r.agent,r.agency].filter(Boolean).join(' · '),12,161,270,10);text(d,'Checked: '+(r.checked||'Not recorded'),12,173,270,9);let x=12;for(const [label,url]of [['Eurobasket',r.eurobasket],['Player profile',r.profile],['Source',r.source]])if(url){d.setTextColor(24,112,89);d.textWithLink(label,x,185,{url});x+=60;}d.setTextColor(36,54,59);}}
if(!cards){d.addPage();head(d,'Sources and verification',rows.length);let y=39;for(const r of rows){if(y>177){d.addPage();head(d,'Sources and verification',rows.length);y=39;}text(d,r.name+' · '+r.status,12,y,270,10);y+=7;let x=12;for(const [label,url]of [['Eurobasket',r.eurobasket],['Player profile',r.profile],['Source',r.source]])if(url){d.setTextColor(24,112,89);d.setFontSize(9);d.textWithLink(label,x,y,{url});x+=65;}d.setTextColor(36,54,59);y+=12;}}
if(includeNotes){for(const r of rows){const notes=[['Athleticism','nAth'],['Offense','nOff'],['Defense','nDef'],['Verdict','nProj']].filter(([,k])=>r.notes?.[k]);if(!notes.length)continue;d.addPage();head(d,'Scouting notes · '+r.name,rows.length);let y=40;for(const [label,k]of notes){d.setFontSize(10);const lines=d.splitTextToSize(label+'\n'+String(r.notes[k]),270);for(const line of lines){if(y>188){d.addPage();head(d,'Scouting notes · '+r.name,rows.length);y=40;}text(d,line,12,y,270,10);y+=5;}y+=7;}}}foot(d);download(d.output('arraybuffer'),'application/pdf',cards?'cards.pdf':'comparison.pdf');}
function menu(){const rows=snapshot();showModal('<h3>Export candidates</h3><p>'+rows.length+' players · all matching results, in the current sort order.</p><div class="es-export-options"><button class="btn" data-export="xlsx">Excel workbook <small>Formatted shortlist, complete basic statistics and sources</small></button><button class="btn" data-export="pdf">PDF comparison <small>Player overview, box scores, shooting and source links</small></button><button class="btn" data-export="cards">PDF player cards <small>One player per page, including all basic statistics</small></button></div><label><input type="checkbox" id="exportNotes"> Include saved scouting notes</label><p class="hint" id="exportProgress" role="status">Statistics use each player’s displayed league and season.</p>',true);document.querySelectorAll('[data-export]').forEach(b=>b.onclick=async()=>{const status=document.getElementById('exportProgress');if(!rows.length){status.textContent='No matching players to export.';return;}document.querySelectorAll('[data-export]').forEach(x=>x.disabled=true);status.textContent='Preparing your export…';try{if(b.dataset.export==='xlsx')await excel(rows,document.getElementById('exportNotes').checked);else await pdf(rows,b.dataset.export==='cards',document.getElementById('exportNotes').checked);status.textContent='Export ready. Check your downloads.';}catch(e){status.textContent=e.message||'Export failed. Please try again.';}finally{document.querySelectorAll('[data-export]').forEach(x=>x.disabled=false);}});}
window.EuroScoutExport={menu,snapshot,excel,pdf,stats:STATS,values};
})();
