/* Destination identities only: never inject these clubs into historical standings. */
(function(){
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const directory=()=>[...(window.EUROSCOUT_CLUB_DIRECTORY||[]),...Object.values(ovrMerged().clubs||{}).filter(d=>d&&d.id&&d.name&&d.country).map(d=>({...d,aliases:d.aliases||[]}))];
let signature='';
function refresh(){const s=JSON.stringify(ovrMerged().clubs||{});if(s===signature)return;signature=s;DBTEAM_LIST=null;DBTEAM_BYKEY=null;CLUBS=null;CLUB_BY_TEAMKEY=null;}
function addForm(done){if(!Store.canEdit()){toast('Editing access required.');return;}document.getElementById('clubCreateOverlay')?.remove();const mask=document.createElement('div');mask.id='clubCreateOverlay';mask.style.cssText='position:fixed;inset:0;background:#0008;z-index:100000;display:grid;place-items:center;padding:16px';mask.innerHTML='<form style="background:var(--card,#fff);color:var(--text,#17303b);padding:24px;border-radius:16px;width:min(440px,100%);max-height:90vh;overflow:auto"><h3>Add missing club</h3><label>Club name<input name="club" required maxlength="150" style="display:block;width:100%"></label><label>Country<input name="country" required maxlength="80" style="display:block;width:100%"></label><label>League<input name="league" required maxlength="120" style="display:block;width:100%"></label><p class="hint">This adds a destination club. It does not import statistics or standings.</p><p role="status"></p><button type="button" class="btn">Cancel</button> <button type="submit" class="btn">Add club</button></form>';document.body.append(mask);const close=()=>{mask.remove();window.removeEventListener('keydown',escKey,true);};const escKey=e=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close();}};window.addEventListener('keydown',escKey,true);mask.querySelector('button').onclick=close;mask.onclick=e=>{if(e.target===mask)close();};mask.querySelector('input').focus();mask.querySelector('form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,name=f.elements.club.value.trim(),country=EuroScoutCountries.canonical(f.elements.country.value.trim()),league=f.elements.league.value.trim();if(!name||!country||!league){f.querySelector('[role=status]').textContent='Enter a club name, a recognised country and league.';return;}const existing=allDbTeams().find(t=>norm(t.name)===norm(name)&&norm(EuroScoutCountries.canonical(t.country))===norm(country));if(existing){close();done(canonKey(existing.key));toast('Selected the existing club.');return;}const id='custom-'+crypto.randomUUID();ovrSaveLocal({clubs:{[id]:{id,name,country,league,aliases:[],source:'',checked:new Date().toISOString().slice(0,10)}}});refresh();const k=canonKey('directory|'+id);close();done(k);toast('Club added.');};}
const redirects=new Map();
function extend(out){redirects.clear();for(const d of directory()){
 const names=[d.name,...d.aliases].map(norm);
 // Only an exact full-name/explicit alias match is eligible. No city or nickname guessing.
 const country=s=>window.EuroScoutCountries?.canonical(s)||s;
 const matches=out.filter(t=>!t.directoryOnly&&names.includes(norm(t.name))&&(!t.country||norm(country(t.country))===norm(country(d.country))));
 if(matches.length){for(const t of matches)t.searchAliases=[...(t.searchAliases||[]),d.name,...d.aliases];redirects.set('directory|'+d.id,matches[0].key);continue;}
 out.push({key:'directory|'+d.id,code:d.id,lg:'directory',lgName:d.league,name:d.name,country:d.country,city:'',logo:null,directoryOnly:true,source:d.source,searchAliases:d.aliases});
}}
function linkAliases(teamMap,clubMap){for(const [old,key]of redirects){teamMap.set(old,teamMap.get(key));clubMap.set(old,clubMap.get(key));}}
function open(key){const t=dbTeamByKey(key);if(t&&key.startsWith('directory|')&&!t.directoryOnly){openTeamIn(t.lg,t.code);return true;}if(!t?.directoryOnly)return false;
 const people=assignPool().filter(p=>effective26keys(p).includes(canonKey(key)));
 showModal(`<h3>${esc(t.name)}</h3><p>${esc(t.country)} · ${esc(t.lgName)}</p><p class="hint">Destination club directory. No statistics have been imported. League labels identify the source directory, not confirmed 2026/27 competition entry.</p><p>${/^https?:\/\//.test(t.source||'')?`<a href="${escAttr(t.source)}" target="_blank" rel="noopener noreferrer">Club source ↗</a>`:'Added manually'}</p><h4>Assigned for 2026/27 · ${people.length}</h4>${people.length?people.map(p=>`<p><button class="btn" data-directory-player="${escAttr(p.id)}">${esc(p.name)}</button></p>`).join(''):'<p>No players assigned yet.</p>'}`);
 document.querySelectorAll('[data-directory-player]').forEach(b=>b.onclick=()=>{hideModal();openProfile(b.dataset.directoryPlayer);});return true;
}
window.EuroScoutClubs={extend,open,linkAliases,refresh,addForm};
})();
